apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubehello
  labels:
    k8s-app: kubehello
spec:
  replicas: 5

  template:
    metadata:
      name: kubehello
      labels:
        k8s-app: kubehello
    spec:
      containers:
        - image: tarkalabsdeploy/kubehello:0.3.0
          imagePullPolicy: Always
          name: kubehello
          ports:
            - containerPort: 4343
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

